version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "soemo"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "soemo"
