default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: tippspiel_development_wm2022

test:
  <<: *default
  database: tippspiel_test

# prod db == dev db
production:
  <<: *default
  database: tippspiel_development_wm2022 # hier nutzen wir auch lokal unser dev DB