default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8mb4

development:
  adapter: mysql2
  username: root
  password:
  host: 127.0.0.1
  database: tippspiel_development_wm_2026

test:
  adapter: sqlite3
  database: tmp/test.sqlite3

production:
  adapter: mysql2
  username: root
  password:
  host: 127.0.0.1
  database: tippspiel_development_wm_2026
